modLoader="javafml"
loaderVersion="${target_loader}"
issueTrackerURL="https://github.com/IMB11/Sounds/issues"
displayURL="http://IMB11.dev/"
logoFile="assets/sounds/icon.png"
authors="IMB11"
license="All-Rights-Reserved"

[[mods]]
modId="sounds"
version="${mod_version}"
displayName="Sounds"
description="A highly configurable sound overhaul mod that adds new sound effects while improving vanilla sounds too."

[[dependencies.sounds]]
modId="${loader}"
${mandatory_inclusion_field}
versionRange="${target_loader}"
ordering="NONE"
side="BOTH"

[[dependencies.sounds]]
modId="minecraft"
${mandatory_inclusion_field}
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies.sounds]]
modId="mru"
${mandatory_inclusion_field}
versionRange="${target_mru}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="sounds.mixins.json"