name: Bug report
description: Found an issue with the mod or encountered an incompatibility?
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        ***


        # Important Compatibility Note


        This mod is built and tested using a specific mod loader or environment.
        It may not be compatible with other loaders or setups. Using it outside
        its intended environment can lead to unexpected issues, crashes, or
        incompatibilities that we might be unable to troubleshoot.


        If you are experiencing problems while using a different mod loader or
        an unsupported environment, please note that we may not be able to
        provide a fix for that scenario.


        **Our focus and resources are dedicated to ensuring the mod runs
        smoothly within the environment it was designed for.**


        ***
  - type: checkboxes
    id: read
    attributes:
      label: Have you read the information above?
      options:
        - label: 'Yes'
          required: true
  - type: dropdown
    id: loader
    attributes:
      label: Loader
      description: Which mod loader are you using?
      options:
        - Fabric
        - Forge
        - NeoForge
        - Quilt
        - Other
    validations:
      required: true
  - type: checkboxes
    id: sinytra_connector
    attributes:
      label: Sinytra Connector
      description: Are you using Sinytra Connector?
      options:
        - label: 'Yes, I am using Sinytra Connector'
      # No 'required' attribute, so this field is optional.
  - type: input
    id: game_version
    attributes:
      label: Game Version
      description: What version of the game are you running? (e.g., 1.20.1)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Provide your logs.
      description: >-
        Please use [mclo.gs](https://mclo.gs/) to upload your logs and paste the
        link here. Even if there are no crashes, logs help identify version
        details and potential error messages.

        **Do not paste raw logs directly here** as they may contain sensitive
        information.
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue.
      description: >-
        Provide a detailed description of the issue you're encountering. Feel
        free to include images or videos to better illustrate the problem.
      placeholder: The mod crashes when I ...
    validations:
      required: true
