name: Bug report
description: Found an issue with the mod or encountered an incompatibility?
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        ***


        # Important Compatibility Note


        This mod is built and tested using a specific mod loader or environment.
        It may not be compatible with other loaders or setups. Using it outside
        its intended environment can lead to unexpected issues, crashes, or
        incompatibilities that we might be unable to troubleshoot.


        If you are experiencing problems while using a different mod loader or
        an unsupported environment, please note that we may not be able to
        provide a fix for that scenario.


        **Our focus and resources are dedicated to ensuring the mod runs
        smoothly within the environment it was designed for.**


        ***
  - type: checkboxes
    id: read
    attributes:
      label: Have you read the information above?
      options:
        - label: 'Yes'
          required: true
  - type: dropdown
    id: loader
    attributes:
      label: Loader
      description: Which mod loader are you using?
      options:
        - Fabric
        - Forge
        - NeoForge
        - Quilt
        - Other
    validations:
      required: true
  - type: checkboxes
    id: sinytra_connector
    attributes:
      label: Sinytra Connector
      description: Are you using Sinytra Connector?
      options:
        - label: 'Yes, I am using Sinytra Connector'
  - type: dropdown
    id: game_version
    attributes:
      label: Game Version
      description: What version of the game are you running?
      options:
        - 1.20
        - 1.20.1
        - 1.21
        - 1.21.1
        - 1.21.2
        - 1.21.3
        - 1.21.4
    validations:
      required: true
  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: Which version of this mod are you using? (e.g., 1.0.0)
    validations:
      required: true
  - type: dropdown
    id: environment_type
    attributes:
      label: Environment Type
      description: What environment are you experiencing this issue in?
      options:
        - Singleplayer
        - Multiplayer (Client)
        - Multiplayer (Server)
        - Other (Specify in Describe Your Issue)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Provide your logs.
      description: >-
        Please use [mclo.gs](https://mclo.gs/) to upload your logs and paste the
        link here. Even if there are no crashes, logs help identify version
        details and potential error messages.

        **Do not paste raw logs directly here** as they may contain sensitive
        information.
    validations:
      required: true
  - type: textarea
    id: other_mods
    attributes:
      label: Other Installed Mods
      description: List other mods you have installed, if any. (Optional)
      placeholder: e.g., ModA, ModB, ModC
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue.
      description: >-
        Provide a detailed description of the issue you're encountering. Feel
        free to include images or videos to better illustrate the problem.
      placeholder: The mod crashes when I ...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the mod to...
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the mod...
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: >-
        Please list the steps that lead to the issue. Be as specific as possible
        so we can attempt to replicate it.
      placeholder: 1. Do X\n2. Do Y\n3. Crash/bug occurs
    validations:
      required: true
